### ISSUE TITLE
Maven Build Error in Eclipse Neon for versions >13.2.0

### ISSUE THREAD

**Issue by lacan** [scijava/pom-scijava#47] opened 2017-07-06 07:03 UTC
If I try to change the version of pom-scijava to anything higher than 13.2.0 I get the following error message, without anything else...

Any help or feedback would be appreciated. 
![image](https://user-images.githubusercontent.com/319932/27899271-d5dd2670-6229-11e7-9a3a-2b85410546dd.png)

**Comment by imagejan** [comment] 2017-07-06 07:58
Hi @lacan,

can you try:

* building from the command line with `mvn` (or `mvn clean install`) to see whether this gives an error as well?
* updating your maven project in eclipse (using <kbd>Alt</kbd><kbd>F5</kbd> or right-click on the project *> Maven > Update Project...*)?

**Comment by stelfrich** [comment] 2017-08-28 11:08
Hi @lacan,

I could not reproduce the issue with the latest commit in

**Comment by ctrueden** [comment] 2017-08-28 18:16
Closing proactively. But @lacan, please reopen with an [MCVE](https://imagej.net/Bug_reporting_best_practices) if this continues to be a problem for you!

**Closed by ctrueden** 2017-08-28 18:16 UTC
